### ISSUE TITLE
Convert error handling code

### ISSUE THREAD

**Issue by sertel** [sertel/smoltcp#6]
Most of the code in `egress` and probably also in `ingress` propagates errors.
We need to find a way to represent this properly in our programming model.

**Comment by sertel** [comment]
For the first prototype, we are not paying much attention to error handling.
We acknowledge that most error handling is barely syntactic sugar for early returns. Nevertheless, the according transformations may not be as trivial as they seem.

For now, just panic away! :)

**Comment by Pagolin** [comment]
Errors where basically internally propagated and finally led to either stop doing something e.g. stop looping over the sockets for sending or merely resulted in a log message. So this is all well encapsulated and handled in our stateful components.
